export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};

export const AUTH_RETRY_PERIOD_IN_MINUTES = 300000;
export const AUTH_MAX_RETRY_TIMES = 3;
